root: true

env:
  browser: true
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module
  impliedStrict: true

extends:
  - eslint:recommended
  - plugin:svelte/recommended
  - plugin:tailwindcss/recommended

overrides: []

rules:
  # JS
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  jsx-quotes:
    - error
    - prefer-single
  semi:
    - error
    - never

  array-callback-return: 2
  no-await-in-loop: 2
  no-cond-assign:
    - 2
    - always
  no-constant-binary-expression: 2
  no-constructor-return: 2
  no-duplicate-imports: 2
  no-promise-executor-return: 2
  no-self-compare: 2
  no-template-curly-in-string: 2
  no-unmodified-loop-condition: 2
  no-unreachable-loop: 1
  no-unused-private-class-members: 1
  no-use-before-define: 2
  require-atomic-updates: 1

  accessor-pairs: 2
  arrow-body-style:
    - 2
    - as-needed
  block-scoped-var: 2
  camelcase:
    - 2
    - properties: never

  complexity:
    - 2
    - 10
  consistent-return: 0
  consistent-this:
    - 2
    - _this
  curly:
    - 2
    - multi-line
  default-case: 2
  default-case-last: 2
  default-param-last: 2
  dot-notation: 2
  eqeqeq: 2
  func-names:
    - 2
    - as-needed
  func-style:
    - 2
    - declaration
    - allowArrowFunctions: true
  grouped-accessor-pairs:
    - 2
    - getBeforeSet
  logical-assignment-operators: 2
  max-nested-callbacks:
    - 2
    - 4
  max-params:
    - 2
    - 3

  no-alert: 2
  no-array-constructor: 2
  no-bitwise: 1
  no-caller: 2
  no-confusing-arrow: 1
  no-console: 0
  no-div-regex: 2
  no-else-return: 2
  no-empty-function: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implicit-globals: 2
  no-implied-eval: 2
  no-invalid-this: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-mixed-operators: 1
  no-multi-assign: 2
  no-nested-ternary: 2
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-proto: 2
  no-restricted-syntax:
    - 2
    - selector: CallExpression[callee.object.name='console'][callee.property.name=/^(debug|info|log|warn|trace)$/]
  no-return-assign: 2
  no-return-await: 0
  no-script-url: 2
  no-sequences: 2
  no-shadow: 1
  no-throw-literal: 2
  no-undef-init: 2
  no-unneeded-ternary: 2
  no-unused-expressions:
    - 2
    - allowShortCircuit: true
  no-useless-call: 2
  no-useless-computed-key: 2
  no-useless-concat: 2
  no-useless-constructor: 1
  no-useless-rename: 2
  no-useless-return: 2
  no-var: 2
  no-void: 2
  object-shorthand: 2
  one-var:
    - 2
    - uninitialized: consecutive
      initialized: never
  operator-assignment: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  prefer-destructuring:
    - 2
    - VariableDeclarator:
        array: true
        object: true
      AssignmentExpression:
        array: true
        object: false
    - enforceForRenamedProperties: false
  prefer-exponentiation-operator: 2
  prefer-named-capture-group: 1
  prefer-numeric-literals: 1
  prefer-object-has-own: 2
  prefer-object-spread: 2
  prefer-regex-literals: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  quote-props:
    - 2
    - as-needed
  radix: 2
  require-await: 2
  spaced-comment: 2
  strict: 2
  symbol-description: 2
  yoda:
    - 2
    - never
    - exceptRange: true

  array-bracket-newline:
    - 2
    - multiline: true # Enforce newlines on brackets if content is multiline
  array-bracket-spacing: 2
  arrow-parens:
    - 2
    - as-needed
  arrow-spacing: 2
  block-spacing: 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  comma-spacing: 2
  comma-style:
    - 2
    - last
  computed-property-spacing: 2
  dot-location:
    - 2
    - property
  eol-last: 2
  func-call-spacing: 2
  function-call-argument-newline:
    - 2
    - consistent
  generator-star-spacing: 2
  key-spacing: 2
  keyword-spacing: 2
  lines-between-class-members:
    - 2
    - always
    - exceptAfterSingleLine: true
  max-len:
    - 2
    - code: 120
      comments: 100
      tabWidth: 4
      ignoreTemplateLiterals: true
      ignoreStrings: true
      ignorePattern: '@(param|returns)'
  max-statements-per-line: 2
  new-parens: 2
  no-multi-spaces: 2
  no-multiple-empty-lines:
    - 2
    - max: 1
      maxBOF: 0
      maxEOF: 0
  no-trailing-spaces: 2
  no-whitespace-before-property: 2
  nonblock-statement-body-position: 2
  object-curly-newline:
    - 2
    - multiline: true
  object-curly-spacing:
    - 2
    - always
  padded-blocks:
    - 2
    - never
  rest-spread-spacing: 2
  semi-spacing: 2
  semi-style: 2
  space-before-blocks: 2
  space-before-function-paren:
    - 2
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops: 2
  switch-colon-spacing: 2
  template-curly-spacing: 2
  template-tag-spacing: 2
  wrap-iife:
    - 2
    - inside
  wrap-regex: 2
  yield-star-spacing: 2

  # Svelte
  svelte/button-has-type: 2

  # Tailwind
  tailwindcss/classnames-order: 1
  tailwindcss/enforces-negative-arbitrary-values: 1
  tailwindcss/enforces-shorthand: 1
  tailwindcss/no-arbitrary-value: 0
  tailwindcss/no-custom-classname: 0
  tailwindcss/no-contradicting-classname: 2
